language: java

before_script:
- chmod a+x gradlew

script:
- ./gradlew check
- ./gradlew jacocoTestReport

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/