language: java

before_script:
- chmod a+x gradlew

script:
- ./gradlew jar
- ./gradlew check

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - .autoconf
  - $HOME/.m2